package org.komparator.supplier.ws.cli;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.List;
import java.util.Map;

import javax.xml.ws.BindingProvider;

import org.komparator.security.CryptoUtil;
import org.komparator.supplier.ws.BadProductId_Exception;
import org.komparator.supplier.ws.BadProduct_Exception;
import org.komparator.supplier.ws.BadQuantity_Exception;
import org.komparator.supplier.ws.BadText_Exception;
import org.komparator.supplier.ws.InsufficientQuantity_Exception;
import org.komparator.supplier.ws.ProductView;
import org.komparator.supplier.ws.PurchaseView;
import org.komparator.supplier.ws.SupplierPortType;
import org.komparator.supplier.ws.SupplierService;

import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINaming;

/**
 * Client port wrapper.
 *
 * Adds easier end point address configuration to the Port generated by
 * wsimport.
 */
public class SupplierClient implements SupplierPortType {

	/** WS service */
	SupplierService service = null;

	/** WS port (port type is the interface, port is the implementation) */
	SupplierPortType port = null;

	/** WS end point address */
	private String wsURL = null; // default value is defined inside WSDL
	
	private String wsname = null;
	private String uddiURL = null;

	public String getWsURL() {
		return wsURL;
	}
	public String getWsName(){
		return wsname;
	}

	/** output option **/
	private boolean verbose = false;

	public boolean isVerbose() {
		return verbose;
	}

	public void setVerbose(boolean verbose) {
		this.verbose = verbose;
	}

	/** constructor with provided web service URL */
	public SupplierClient(String wsURL) throws SupplierClientException {
		this.wsURL = wsURL;
		CryptoUtil.setName("A42_Mediator");
		createStub();
	}
	
	public SupplierClient(String wsname, String uddiURL) throws SupplierClientException {
		this.wsname = wsname;
		this.uddiURL  = uddiURL;
		CryptoUtil.setName("A42_Mediator");
		uddiLookUp();
		createStub();
	}

	/** Stub creation and configuration */
	private void createStub() {
		if (verbose)
			System.out.println("Creating stub ...");
		service = new SupplierService();
		port = service.getSupplierPort();

		if (wsURL != null) {
			if (verbose)
				System.out.println("Setting endpoint address ...");
			BindingProvider bindingProvider = (BindingProvider) port;
			Map<String, Object> requestContext = bindingProvider.getRequestContext();
			requestContext.put(ENDPOINT_ADDRESS_PROPERTY, wsURL);
		}
	}
	
	private void uddiLookUp() throws SupplierClientException {
        try {
            if (verbose) {
                System.out.printf("Connecting UDDI at %s%n", uddiURL);
            }
            UDDINaming uddiNaming = new UDDINaming(uddiURL);

            if (verbose) {
                System.out.printf("Searching '%s'%n", wsname);
            }
            wsURL = uddiNaming.lookup(wsname);

        } catch (Exception e) {
            String msg = String.format("Client failed connecting to UDDI at %s!", uddiURL);
            throw new SupplierClientException(msg, e);
        }

        if (wsURL == null) {
            String msg = String.format("%s not found on UDDI at %s", wsname, uddiURL);
            throw new SupplierClientException(msg);
        }
    }

	// remote invocation methods ----------------------------------------------

	@Override
	public ProductView getProduct(String productId) throws BadProductId_Exception {
		return port.getProduct(productId);
	}

	@Override
	public List<ProductView> searchProducts(String descText) throws BadText_Exception {
		return port.searchProducts(descText);
	}

	@Override
	public String buyProduct(String productId, int quantity)
			throws BadProductId_Exception, BadQuantity_Exception, InsufficientQuantity_Exception {
		return port.buyProduct(productId, quantity);
	}

	@Override
	public String ping(String name) {
		return port.ping(name);
	}

	@Override
	public void clear() {
		port.clear();
	}

	@Override
	public void createProduct(ProductView productToCreate) throws BadProductId_Exception, BadProduct_Exception {
		port.createProduct(productToCreate);
	}

	@Override
	public List<ProductView> listProducts() {
		return port.listProducts();
	}

	@Override
	public List<PurchaseView> listPurchases() {
		return port.listPurchases();
	}

	public void setWsName(String orgName) {
		this.wsname = orgName;
	}

}
